### ISSUE TITLE
Swift Package Fails to Resolve Dependency

### ISSUE THREAD

**Issue by cliftonlabrum** [swiftcsv/SwiftCSV#101]
I've tried this multiple times and restarted Xcode (13.2.1), but I'm still getting this error when I try to add this package:

> _Failed to resolve dependencies_

<img width="417" alt="swiftcsv" src="https://user-images.githubusercontent.com/2513753/151271964-11a5d640-e4f4-4f07-87e4-638ab1eab244.png">

Is anyone else running into this?

**Comment by DivineDominion** [comment]
I've had all kinds of troubles with 13.2.1 -- could you try with 13.3 from yesterday or 13.1?
