### ISSUE TITLE
Delete the v0.7 and develop branches.

### ISSUE THREAD

**Issue by lardieri** [swiftcsv/SwiftCSV#108]
The changes in v0.7 are fully merged to master.

The changes in develop are almost fully merged to master. The remaining unmerged changes involve removing gratuitous whitespace from files. If you think that's desirable, it's easy to accomplish this directly against master using a competent text editor. That will be easier than resolving merge conflicts at this point.

**Comment by DivineDominion** [comment]
To be honest, I didn't check develop in a while. I don't recall why it's behind _and_ ahead  of master, and how we ended up in that situation 🤔

v0.7 is obsolete because you prepared a v0.7.1 release recently, that was super helpful 🙏  

Removed the branches.
