### ISSUE TITLE
Prepare manifest for 0.8.1 release

### ISSUE THREAD

**Issue by lardieri** [swiftcsv/SwiftCSV#112]
So far we have:

- UTF-8 BOM fix
- Serializing alternate delimiters
- ...which requires fixing the build break introduced into non-iOS builds
- Serializing embedded quotes

Is there anything else planned for 0.8.1 ?
Or is it time to proceed with changelog, tags, etc. ?

**Comment by lardieri** [comment]
@DivineDominion  — any other contributors besides yourself who might want to add to the shipping manifest?

**Comment by DivineDominion** [comment]
@lardieri There are no other active contributors at the moment, and no release agenda I'm currently aware of :)

I'm fine with cutting a 0.8.1 release when your PRs are merged. Thanks for all these improvements!
