### ISSUE TITLE
Add Privacy Manifest to SPM and Carthage and CocoaPods build

### ISSUE THREAD

**Issue by DivineDominion** [swiftcsv/SwiftCSV#137]
Resources:

https://www.avanderlee.com/xcode/missing-api-declaration-required-reason-itms-91053/
https://mjtsai.com/blog/2024/04/05/embedding-a-privacy-manifest-into-an-xcframework/
https://www.privacymanifest.dev/
https://www.donnywals.com/how-to-add-a-privacy-manifest-file-to-your-app-for-required-reason-api-usage/

**Comment by lardieri** [comment]
Do we know which specific APIs are getting flagged? (Meaning: do we have a sample email from an App Store upload?)

Otherwise, we just need to audit the code. I'd imagine it's only local file APIs.
