### ISSUE TITLE
Dependency "CSV.swift" has no shared framework schemes for any of the platforms: iOS

### ISSUE THREAD

**Issue by pratik-kate** [swiftcsv/SwiftCSV#140]
I am trying to install CSV.swift dependency using carthage, but facing this issue,
```
Dependency "CSV.swift" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/yaslab/CSV.swift/issues/new
```

I have tried re-installing carthage and the dependency but it is still not working.

Also tried with this command,
`Carthage update --platform iOS`
Any solution to this problem, also if I am missing something please let me know.

**Comment by lardieri** [comment]
Sorry to hear about your build issue, but I think you may be confusing us with a different CSV project.

If you look at the URL in the error message, it appears that you are using this project:
https://github.com/yaslab/CSV.swift

Best of luck!
