### ISSUE TITLE
No account for carriage character in Parser.swift within isNewLine()

### ISSUE THREAD

**Issue by laus102** [swiftcsv/SwiftCSV#36]
![screen shot 2016-05-13 at 3 56 15 pm](https://cloud.githubusercontent.com/assets/5995356/15260196/6caea03e-1923-11e6-8179-74485644769f.png)

This was giving me some trouble with file input.  The attached image is the corrected method implementation.

**Comment by gavanchan** [comment]
Thanks for picking that up, @laus102 !

Some of the semantics behind checking for a newline has been changed in my branch. Along with that, I've interpreted your solution into it as well.

I intend to open a request for that branch into the base fork when Swift 3 migration branches have gone through review.

**Please see the following pull request for the changes and let me know what you think, in the request.**
https://github.com/gavanchan/SwiftCSV/pull/3

**For the specific commits involving the issue you found,** ***please see:***
482804d - Introduction of the change w/ your logic.
85d2592 - Source update with the new change.

**Comment by DivineDominion** [comment]
Fixed already 👍
