### ISSUE TITLE
How do I get the data from a .csv file I import?

### ISSUE THREAD

**Issue by ErikaVasNormandy** [swiftcsv/SwiftCSV#39]
![screen shot 2016-05-17 at 11 40 55 am](https://cloud.githubusercontent.com/assets/8341739/15334650/03091b74-1c24-11e6-8bd9-6fd72a7df183.png)

I need to have an application that can read in the values from a .csv file that I import into the project. Right now, the do statement appears to not work

**Comment by ASCI-Red** [comment]
The app does not crash, but I am trying to access the CSV file using CSV(name: "CSVName"). It isn't executing but just goes right to the catch statement

**Comment by elSpike** [comment]
I'm having exactly the same issue. Just straight to the catch statement.

**Comment by grantkemp** [comment]
I think we need a nice Example project - will look at adding this for the next point release

**Comment by thexande** [comment]
For those on Swift 3:

`
let csvURL = Bundle(for: ViewController.self).url(forResource: "your_csv_file_name", withExtension: "csv")!
            let csv = try CSV(url: csvURL)
`
