### ISSUE TITLE
Issues when trying use SwiftCSV in tvOS

### ISSUE THREAD

**Issue by MansoorB** [swiftcsv/SwiftCSV#45]
"The platform of the target X (tvOS 10.2) is not compatible with SwiftCSV (0.3.2), which does not support tvos."

**Comment by MansoorB** [comment]
"The platform of the target `X` (tvOS 10.2) is not compatible with `SwiftCSV (0.3.2)`, which does not support `tvos`."

**Comment by MansoorB** [comment]
"The platform of the target X (tvOS 10.2) is not compatible with SwiftCSV (0.3.2), which does not support tvos."

**Comment by DivineDominion** [comment]
Since this is so old, I'm closing this issue. If the problem persists with the new podspec (where tvOS is listed since v0.5.0), please reopen or open a new issue
