### ISSUE TITLE
Do you support Swift 3?

### ISSUE THREAD

**Issue by lotfyahmed** [swiftcsv/SwiftCSV#50]
Do you support Swift 3?
I used Cocoa Pod, What is the branch name that I can use after migration to Swift 3?

**Comment by grantkemp** [comment]
@lotfyahmed  @naoty  we now have a Swift 3 verison in the develop branch. Would be great for others to test it and we can release it next week.

**Comment by Daniel-Higgott** [comment]
I too would love Swift 3 support! I can't find a CSV Parser that works with Swift 3, so this would be great! Thanks for all your work.

**Comment by rsavutiu** [comment]
Doesn't work for me.... I get a ton of errors for that branch

**Comment by kdbertel** [comment]
Xcode 9 and Swift 4 release is imminent. Is there any chance that the `develop` branch will get merged to `master` so that Cocoapods points to the right thing?

**Comment by JCMcLovin** [comment]
Will the newest version that supports Swift 4 be merged to master soon?

**Comment by DivineDominion** [comment]
All done :)
