### ISSUE TITLE
Add support for Swift Package Manager

### ISSUE THREAD

**Issue by kgn** [swiftcsv/SwiftCSV#52]
I'd like to use this with Vapor which uses Swift Package Manger for dependencies.

**Comment by grantkemp** [comment]
Hi - its a good idea, but I am not that familiar with with SPM - can you submit a pull request? and we can plan for the release after next?

**Comment by kgn** [comment]
I wasn't familiar with the steps involved with making a package, but after [some reading](https://www.raywenderlich.com/148832/introduction-swift-package-manager) it seems the only thing that's needed is a `Package.swift` file and to put all the source files in a `Sources` directory and move `SwiftCSVTests` into a `Tests` directory. However, when I attempted to do this in a fork I ran into compile issues as the code needs to be updated for Swift 3 and there were some things that didn't automatically convert.

Do you plan on updating the library to Swift 3?

`Package.swift`
``` swift
import PackageDescription

let package = Package(
    name: "SwiftCSV"
)
```

**Comment by wpuricz** [comment]
I would also like to see this as a swift package so that I can use it in Vapor and for command line applications.

**Comment by grantkemp** [comment]
@kgn  we now have a swift 3 version the develop branch.  Do you want to try it out and potentially submit SPM fix against that ? and we can release at same time

**Comment by kgn** [comment]
Finally got around to this: #58

**Comment by DivineDominion** [comment]
Done in #77
