### ISSUE TITLE
Do you support Swift 4?

### ISSUE THREAD

**Issue by lotfyahmed** [swiftcsv/SwiftCSV#61]
Do you support Swift 4?
I used Cocoa Pod, What is the branch name that I can use after migration to Swift 4?

![screen shot 2017-10-24 at 7 05 12 am](https://user-images.githubusercontent.com/3439991/31925536-26c9de84-b892-11e7-94c3-920d74d4a888.png)

This screenshot after using Swift4.

Thanks,

**Comment by soryncrash13** [comment]
I still get that kind of errors. Apparently no swift 4 support so far...

**Comment by DivineDominion** [comment]
Yes, now it works :) See the 0.4.0 tag!
