### ISSUE TITLE
Package Import failure in Xcode 11 b2

### ISSUE THREAD

**Issue by dsperling** [swiftcsv/SwiftCSV#78]
Trying to use version 0.5.0 in Xcode 11 b2 Swift Package integration produces an error:

SwiftCSV.git has no Package.swift manifest for version 0.5.0.

![package-error](https://user-images.githubusercontent.com/7662738/59965373-e8645800-94c1-11e9-8552-64df18fb2717.png)

**Comment by DivineDominion** [comment]
@dsperling do you happen to know what Xcode 11 expects? Did the manifest DSL change so we now have to provide a version parameter or something?

**Comment by dsperling** [comment]
I am not sure what Xcode 11 expects.   I have imported other projects (such as SwiftyJSON) without issue and wanted to pass along the feedback.

**Comment by DivineDominion** [comment]
Found out why -- the SwiftPM package manifest addition was after the tagged v0.5.0 release. I now added a v0.5.1 release with the latest additions. Does it work now?

**Comment by dsperling** [comment]
A different error with 0.5.1
![Screen Shot 2019-06-25 at 9 50 22 AM](https://user-images.githubusercontent.com/7662738/60117329-bb68ad00-972e-11e9-8c60-de5e3a5488e8.png)

**Comment by DivineDominion** [comment]
That's unfortunate. Since I neither am an expert in SwiftPM manifest nor do I have Xcode 11 handy, I'm putting this on the backburner. If you want to give it a shot, you're very welcome to open a PR with changes!

**Comment by DivineDominion** [comment]
@dsperling Had an idea and released `0.5.2` right now. Can you try again? 🤞

**Comment by dsperling** [comment]
Slightly different error.  I expanded the error dialog so you can see the detail.
<img width="729" alt="Screen Shot 2019-06-26 at 7 17 49 AM" src="https://user-images.githubusercontent.com/7662738/60187559-a3526580-97e2-11e9-9dd4-293a4ed4c0d3.png">

**Comment by DivineDominion** [comment]
I hope we're getting there. What about v0.5.4? -- I now have included more Package initializer parameters.

**Comment by dsperling** [comment]
Peeling the onion!
<img width="729" alt="Screen Shot 2019-06-26 at 8 27 04 AM" src="https://user-images.githubusercontent.com/7662738/60193282-3f349f00-97ec-11e9-8ac6-771c9a85519d.png">

**Comment by DivineDominion** [comment]
Please tell me it works now :)

**Comment by dsperling** [comment]
Victory.
<img width="653" alt="Screen Shot 2019-06-27 at 7 22 05 AM" src="https://user-images.githubusercontent.com/7662738/60274107-55099900-98ac-11e9-9dcc-3c5b25c63987.png">

**Comment by DivineDominion** [comment]
Thanks for being my eyes during this process :)
