### ISSUE TITLE
Miss-formed data should throw an error, not call fatalError()

### ISSUE THREAD

**Issue by ThoseGuysInTown** [swiftcsv/SwiftCSV#80]
_Originally posted by @ThoseGuysInTown in https://github.com/swiftcsv/SwiftCSV/issues/37#issuecomment-521591028_

This will allow us to safely deal with error cases instead of instantly crashing the app.

**Comment by ThoseGuysInTown** [comment]
example of bad data: (comes from a link that's supposed to download a CSV file loading an error page instead)

"\n<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n  <meta charset=\"utf-8\">\n  <meta content=\"width=300, initial-scale=1\" name=\"viewport\">\n  <meta name=\"description\" content=\"Create a new spreadsheet and edit with others at the same time -- from your computer, phone or tablet. Get stuff done with or without an internet connection. Use Sheets to edit Excel files. Free from Google.\">\n  <meta name=\"google-site-verification\" content=\"LrdTUW9psUAMbh4Ia074-BPEVmcpBxF6Gwf0MSgQXZs\">\n  <title>Google Sheets - create and edit spreadsheets online, for free.</title>\n  <style>\n  @font-face {\n  font-family: \'Open Sans\';\n  font-style: normal;\n  font-weight: 300;\n  src: local(\'Open Sans Light\'), local(\'OpenSans-Light\'), url(//fonts.gstatic.com/s/opensans/v15/mem5YaGs126MiZpBA-UN_r8OUuhs.ttf) format(\'truetype\');\n}\n@font-face {\n  font-family: \'Open Sans\';\n  font-style: normal;\n  font-weight: 400;\n  src: local(\'Open Sans\'), local(\'OpenSans\'), url(//fonts.gstatic.com/s/opensans/v15/mem8YaGs126MiZpBA-UFVZ0e.ttf) for ..."

**Comment by ThoseGuysInTown** [comment]
Adding the following fixes it for a quick work around but is not a full solution because it is then very difficult to know if the parsing WOULD have failed

```
    /// Load a CSV file from a string
    ///
    /// - parameter string: Contents of the CSV file
    /// - parameter delimiter: Character to split row and header fields by (default is ',')
    /// - parameter loadColumns: Whether to populate the columns dictionary (default is true)
    public init(string: String, delimiter: Character = comma, loadColumns: Bool = true) {
		
// add these two lines
	var cleanText = string
	cleanText = cleanText.replacingOccurrences(of: "\"", with: "", options: NSString.CompareOptions.literal, range: nil)

        self.text = cleanText
        self.delimiter = delimiter
        self.loadColumns = loadColumns
        self.header = CSV.array(text: cleanText, delimiter: delimiter).first ?? []
    }
    
```

**Comment by DivineDominion** [comment]
Thanks for bringing this issue up again! It seems I have not pushed any release since v0.5.1 to CocoaPods and have just done so. v0.5.1 should include 0a5ac63267b79467ef64b94d9209edc8091f93c8 already, which replaces fatalError'ing with throwing. Can you check which version you're using?

**Comment by ThoseGuysInTown** [comment]
Sorry for delay! Yes it's been fixed, thank you very much! ❤
