### ISSUE TITLE
It may be of interest that SwiftCSV runs on a linux plattform too

### ISSUE THREAD

**Issue by mschrettenbrunner** [swiftcsv/SwiftCSV#82]
I made minor changes in ParsingState.swift: 

all relevant lines from: if char == "\"" {

to: if char == "\u{005c}" {

**Comment by DivineDominion** [comment]
Cool! Would you like to create a PR for this? Linux support sounds great. Maybe I can figure out how to add this to CI 🤔

**Comment by mschrettenbrunner** [comment]
... I appreciate your code :-) and use it in a linux environment with Swift4TF (CUDA)

**Comment by DivineDominion** [comment]
Cool! :) Would you be interested in a PR? Universal platform support would be grat!

If not, I'd close this issue for now, with two very sad eyes :)

**Comment by mschrettenbrunner** [comment]
@DivineDominion Thanks for following up. No  need to have sad eyes : -) Code runs flawless. I will do it as soon as I've finished some tasks
Regards Manfred

**Comment by DivineDominion** [comment]
@mschrettenbrunner did you make progress on this? Don't want to bug, am just considering how to plan the next point release.

**Comment by mschrettenbrunner** [comment]
@DivineDominion, thanks for following up :-)  If you want to accelerate, you may provide a pure data file as a test case for validation of compatibility in my enviroment.

**Comment by DivineDominion** [comment]
@mschrettenbrunner I mostly rely on the unit tests. Some more fixtures would be great, but since they're not there, the unit tests are the best benchmark for cross-platform compatibility. I'll close this issue for now and we await your PR!
