### ISSUE TITLE
How to loop through rows of parsed CSV

### ISSUE THREAD

**Issue by nikhilpandey4** [swiftcsv/SwiftCSV#83]
I want to loop through the rows of the parsed CSV but its not working as CSV does not conform to the Sequence protocol. Please help.

**Comment by DivineDominion** [comment]
Have a look at `CSV.enumeratedRows` or `CSV.namedRows`. I have a PR #76 open where you would end up with just `CSV.rows`.

Conforming to `Sequence` would be a good idea since I do think enumeration by rows is the most common use case.

**Comment by nikhilpandey4** [comment]
Yes. Thats the case and it'll be a great refactor and enhance the longevity of SwiftCSV framework.

**Comment by DivineDominion** [comment]
Confirmed. Do the available properties work for you now?
