### ISSUE TITLE
How to support multiple header rows

### ISSUE THREAD

**Issue by nikhilpandey4** [swiftcsv/SwiftCSV#84]
I have a CSV file where first three rows are header (primary header, followed by secondary header followed by the tertiary header). How to use SwiftCSV in such case?

**Comment by DivineDominion** [comment]
In that case, I'd parse the CSV with headers/named columns _disabled_ and then use `enumeratedRows.dropFirst(3)` to get to the content, and `enumeratedRows[...3]` to get to the header. I'd wrap this is my own data structure to provide more meaningful access to the resulting table.

**Comment by nikhilpandey4** [comment]
Can you please explain by example. Am trying to do what you are telling but somehow its not behaving as it should. Some of my data points are getting cut.

**Comment by DivineDominion** [comment]
Could you provide a "minimum breaking example" CSV file and show what the `print` output is, and what you'd expect? That would be helpful!

**Comment by DivineDominion** [comment]
Closed for now due to inactivity
