### ISSUE TITLE
Not Compatible with SwiftUI

### ISSUE THREAD

**Issue by nicelion** [swiftcsv/SwiftCSV#89]
`public protocol View` in CSV.swift causes an error in SwiftUI Projects due to `View` already being used in SwiftUI. Please consider changing the name.

**Comment by BenLeggiero** [comment]
This definitely should be changed. In the meantime, you can use `SwiftUI.View` and `CSV.View` to disambiguate. That's why Swift doesn't have `NS` and stuff everywhere! 😄

**Comment by DivineDominion** [comment]
`CSVView` wouldn't hurt, I think. Prs welcome!
